# Lumo UI Plugin
# This file is used to store configurations for the Lumo UI Plugin
# Do not delete this file

ThemeName=AppTheme
ComponentsDir=app/src/main/java/com/bluemix/quizassignment/core/ui
PackageName=ui
# Uncomment this line if you are using Kotlin Multiplatform
# KotlinMultiplatform=false
